version: '3'
services:
  app:
    image: node:8.11
    depends_on:
      - mongo
    tty: true
    working_dir: /app
    ports:
      - "${PORT-8937}:${PORT-8937}"
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
    restart: on-failure
    entrypoint: node_modules/.bin/gulp
    environment:
      NODE_ENV: development
      PORT: ${PORT-8937}
      MONGO_DSN: ${MONGO_DSN-mongodb://mongo:27017}
  mongo:
    image: mongo:3.4
    volumes:
      - mongodb:/data/db
    ports:
      - "${BASE4_GRAPH_DB_PORT-8412}:27017"
volumes:
  node_modules: {}
  mongodb: {}
